package com.example.data.repository

import com.example.data.local.dao.NoteDao
import com.example.data.local.dao.VocabularyDao
import com.example.data.local.entity.NoteEntity
import com.example.data.local.entity.VocabularyEntity
import com.example.domain.model.NoteSourceType
import kotlinx.coroutines.flow.Flow
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class NoteRepository(
    private val noteDao: NoteDao,
    private val vocabularyDao: VocabularyDao
) {
    val allActiveNotes: Flow<List<NoteEntity>> = noteDao.getAllActiveNotes()
    val pinnedNotes: Flow<List<NoteEntity>> = noteDao.getPinnedNotes()
    val archivedNotes: Flow<List<NoteEntity>> = noteDao.getArchivedNotes()
    val allVocabulary: Flow<List<VocabularyEntity>> = vocabularyDao.getAllVocabulary()

    fun getNoteById(id: Long): Flow<NoteEntity?> = noteDao.getNoteById(id)

    suspend fun getNoteByIdDirect(id: Long): NoteEntity? = noteDao.getNoteByIdDirect(id)

    fun searchNotes(query: String): Flow<List<NoteEntity>> = noteDao.searchNotes(query)

    suspend fun saveNote(note: NoteEntity): Long = noteDao.insertNote(note)

    suspend fun updateNote(note: NoteEntity) = noteDao.updateNote(note)

    suspend fun updateNoteTitle(id: Long, newTitle: String) {
        val note = noteDao.getNoteByIdDirect(id) ?: return
        val updated = note.copy(
            title = newTitle.trim(),
            titleWasAutoGenerated = false,
            updatedAt = System.currentTimeMillis()
        )
        noteDao.updateNote(updated)
    }

    suspend fun updateNoteBody(id: Long, newBody: String) {
        val note = noteDao.getNoteByIdDirect(id) ?: return
        val wordCount = newBody.trim().split("\\s+".toRegex()).count { it.isNotBlank() }
        val updated = note.copy(
            body = newBody.trim(),
            wordCount = wordCount,
            updatedAt = System.currentTimeMillis()
        )
        noteDao.updateNote(updated)
    }

    suspend fun togglePin(id: Long, currentPin: Boolean) {
        noteDao.updatePinStatus(id, !currentPin)
    }

    suspend fun toggleArchive(id: Long, currentArchived: Boolean) {
        noteDao.updateArchiveStatus(id, !currentArchived, System.currentTimeMillis())
    }

    suspend fun deleteNote(id: Long) {
        val note = noteDao.getNoteByIdDirect(id)
        if (note != null && !note.audioFilePath.isNullOrBlank()) {
            try {
                val file = File(note.audioFilePath)
                val parentName = file.parentFile?.name
                if (file.exists() && (parentName == "recordings" || parentName == "imported_audio")) {
                    file.delete()
                }
            } catch (e: Exception) {
                // Ignore audio deletion error
            }
        }
        noteDao.deleteNoteById(id)
    }

    suspend fun deleteAllNotes() = noteDao.deleteAllNotes()

    suspend fun getVocabularyTermsDirect(): List<String> = vocabularyDao.getAllTermsDirect()

    suspend fun addVocabularyTerm(term: String, category: String = "General"): Long =
        vocabularyDao.insertTerm(VocabularyEntity(term = term.trim(), category = category))

    suspend fun deleteVocabularyTerm(id: Long) = vocabularyDao.deleteTermById(id)

    fun formatExportContent(item: NoteEntity, format: ExportFormat): String {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        val dateStr = dateFormat.format(Date(item.createdAt))
        val isAudio = item.getSourceTypeEnum() != NoteSourceType.TEXT

        return when (format) {
            ExportFormat.TXT -> {
                val header = buildString {
                    appendLine("Title: ${item.title}")
                    appendLine("Date: $dateStr")
                    appendLine("Source: ${item.sourceType}")
                    if (isAudio && item.provider != null) {
                        appendLine("Provider: ${item.provider} (${item.model ?: ""})")
                    }
                    appendLine("--------------------------------------------------")
                }
                """
                $header
                ${item.body}
                """.trimIndent()
            }
            ExportFormat.MARKDOWN -> {
                val meta = buildString {
                    appendLine("# ${item.title}")
                    appendLine()
                    appendLine("- **Date**: $dateStr")
                    appendLine("- **Source**: ${item.sourceType}")
                    if (isAudio && item.provider != null) {
                        appendLine("- **Provider**: ${item.provider} (`${item.model ?: ""}`)")
                    }
                    appendLine()
                    appendLine("---")
                }
                """
                $meta
                ${item.body}
                """.trimIndent()
            }
            ExportFormat.SRT -> {
                """
                1
                00:00:00,000 --> ${formatSrtTimestamp(item.durationMs.coerceAtLeast(1000L))}
                ${item.body}
                """.trimIndent()
            }
            ExportFormat.VTT -> {
                """
                WEBVTT

                00:00:00.000 --> ${formatVttTimestamp(item.durationMs.coerceAtLeast(1000L))}
                ${item.body}
                """.trimIndent()
            }
        }
    }

    private fun formatSrtTimestamp(ms: Long): String {
        val totalSecs = (ms / 1000).coerceAtLeast(1)
        val hours = totalSecs / 3600
        val mins = (totalSecs % 3600) / 60
        val secs = totalSecs % 60
        val millis = ms % 1000
        return String.format(Locale.US, "%02d:%02d:%02d,%03d", hours, mins, secs, millis)
    }

    private fun formatVttTimestamp(ms: Long): String {
        val totalSecs = (ms / 1000).coerceAtLeast(1)
        val hours = totalSecs / 3600
        val mins = (totalSecs % 3600) / 60
        val secs = totalSecs % 60
        val millis = ms % 1000
        return String.format(Locale.US, "%02d:%02d:%02d.%03d", hours, mins, secs, millis)
    }
}
