package com.example.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.domain.model.NoteSourceType

@Entity(tableName = "notes")
data class NoteEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val body: String,
    val sourceType: String = NoteSourceType.VOICE.name, // VOICE, TEXT, IMPORTED_AUDIO
    val audioFilePath: String? = null,
    val originalFileName: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val durationMs: Long = 0L,
    val provider: String? = null,
    val model: String? = null,
    val detectedLanguages: String? = null,
    val processingTimeMs: Long? = null,
    val wordCount: Int = 0,
    val isPinned: Boolean = false,
    val isArchived: Boolean = false,
    val isFavorite: Boolean = false,
    val titleWasAutoGenerated: Boolean = true,
    val titleConfidence: Float = 0.8f,
    val suggestedKeywords: String = "" // Comma-separated or serialized keywords
) {
    fun getSourceTypeEnum(): NoteSourceType {
        return try {
            NoteSourceType.valueOf(sourceType)
        } catch (e: Exception) {
            NoteSourceType.VOICE
        }
    }
}

@Deprecated("Replaced by NoteEntity in Database v2")
@Entity(tableName = "transcriptions")
data class TranscriptionEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val transcript: String,
    val audioFilePath: String,
    val originalFileName: String,
    val createdAt: Long = System.currentTimeMillis(),
    val durationMs: Long,
    val provider: String,
    val model: String,
    val detectedLanguages: String,
    val processingTimeMs: Long,
    val isFavorite: Boolean = false,
    val wordCount: Int = 0
)

@Entity(tableName = "vocabulary")
data class VocabularyEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val term: String,
    val category: String = "General",
    val createdAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "usage_stats")
data class UsageStatEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val dateString: String, // e.g. "2026-09-22"
    val providerName: String,
    val durationMs: Long
)
