package com.example.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.data.local.dao.NoteDao
import com.example.data.local.dao.TranscriptionDao
import com.example.data.local.dao.UsageStatDao
import com.example.data.local.dao.VocabularyDao
import com.example.data.local.entity.NoteEntity
import com.example.data.local.entity.TranscriptionEntity
import com.example.data.local.entity.UsageStatEntity
import com.example.data.local.entity.VocabularyEntity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

@Database(
    entities = [
        NoteEntity::class,
        TranscriptionEntity::class,
        VocabularyEntity::class,
        UsageStatEntity::class
    ],
    version = 2,
    exportSchema = false
)
abstract class AppDatabase : RoomDatabase() {
    abstract fun noteDao(): NoteDao
    abstract fun transcriptionDao(): TranscriptionDao
    abstract fun vocabularyDao(): VocabularyDao
    abstract fun usageStatDao(): UsageStatDao

    companion object {
        @Volatile
        private var INSTANCE: AppDatabase? = null

        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                // 1. Create the new notes table
                db.execSQL("""
                    CREATE TABLE IF NOT EXISTS `notes` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `title` TEXT NOT NULL,
                        `body` TEXT NOT NULL,
                        `sourceType` TEXT NOT NULL,
                        `audioFilePath` TEXT,
                        `originalFileName` TEXT,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL,
                        `durationMs` INTEGER NOT NULL,
                        `provider` TEXT,
                        `model` TEXT,
                        `detectedLanguages` TEXT,
                        `processingTimeMs` INTEGER,
                        `wordCount` INTEGER NOT NULL,
                        `isPinned` INTEGER NOT NULL,
                        `isArchived` INTEGER NOT NULL,
                        `isFavorite` INTEGER NOT NULL,
                        `titleWasAutoGenerated` INTEGER NOT NULL,
                        `titleConfidence` REAL NOT NULL,
                        `suggestedKeywords` TEXT NOT NULL
                    )
                """.trimIndent())

                // 2. Safely migrate all historical transcriptions into notes
                try {
                    db.execSQL("""
                        INSERT INTO `notes` (
                            `id`, `title`, `body`, `sourceType`, `audioFilePath`, `originalFileName`, 
                            `createdAt`, `updatedAt`, `durationMs`, `provider`, `model`, 
                            `detectedLanguages`, `processingTimeMs`, `wordCount`, `isPinned`, 
                            `isArchived`, `isFavorite`, `titleWasAutoGenerated`, `titleConfidence`, `suggestedKeywords`
                        )
                        SELECT 
                            `id`, 
                            `title`, 
                            `transcript` AS `body`, 
                            CASE 
                                WHEN `originalFileName` LIKE 'rec_%.m4a' THEN 'VOICE'
                                ELSE 'IMPORTED_AUDIO'
                            END AS `sourceType`, 
                            `audioFilePath`, 
                            `originalFileName`, 
                            `createdAt`, 
                            `createdAt` AS `updatedAt`, 
                            `durationMs`, 
                            `provider`, 
                            `model`, 
                            `detectedLanguages`, 
                            `processingTimeMs`, 
                            `wordCount`, 
                            0 AS `isPinned`, 
                            0 AS `isArchived`, 
                            `isFavorite`, 
                            1 AS `titleWasAutoGenerated`, 
                            0.8 AS `titleConfidence`, 
                            '' AS `suggestedKeywords`
                        FROM `transcriptions`
                    """.trimIndent())
                } catch (e: Exception) {
                    // Ignore if transcriptions table was empty or not present
                }
            }
        }

        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "voice_transcriber_db"
                )
                .addMigrations(MIGRATION_1_2)
                .addCallback(object : RoomDatabase.Callback() {
                    override fun onCreate(db: SupportSQLiteDatabase) {
                        super.onCreate(db)
                        CoroutineScope(Dispatchers.IO).launch {
                            val defaultVocab = listOf(
                                VocabularyEntity(term = "PR", category = "Business"),
                                VocabularyEntity(term = "BOQ", category = "Engineering"),
                                VocabularyEntity(term = "Variation Order", category = "Engineering"),
                                VocabularyEntity(term = "RFI", category = "Engineering"),
                                VocabularyEntity(term = "Shop Drawing", category = "Engineering"),
                                VocabularyEntity(term = "Mockup", category = "Design"),
                                VocabularyEntity(term = "Gypsum Board", category = "Construction"),
                                VocabularyEntity(term = "Piatra", category = "Materials"),
                                VocabularyEntity(term = "Galala", category = "Materials"),
                                VocabularyEntity(term = "Palmariva", category = "Locations"),
                                VocabularyEntity(term = "Negma", category = "Locations"),
                                VocabularyEntity(term = "New Cairo", category = "Locations"),
                                VocabularyEntity(term = "Quotation", category = "Business"),
                                VocabularyEntity(term = "Contractor", category = "Business"),
                                VocabularyEntity(term = "Meeting", category = "General"),
                                VocabularyEntity(term = "Approval", category = "Business")
                            )
                            getDatabase(context).vocabularyDao().insertTerms(defaultVocab)
                        }
                    }
                }).build()
                INSTANCE = instance
                instance
            }
        }
    }
}
