package com.example

import androidx.compose.foundation.layout.padding
import androidx.compose.ui.Modifier
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onRoot
import androidx.compose.ui.unit.dp
import com.example.data.local.entity.NoteEntity
import com.example.domain.model.NoteSourceType
import com.example.ui.screens.NoteCard
import com.example.ui.theme.MyApplicationTheme
import com.github.takahirom.roborazzi.RobolectricDeviceQualifiers
import com.github.takahirom.roborazzi.captureRoboImage
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode

@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(qualifiers = RobolectricDeviceQualifiers.Pixel8, sdk = [36])
class GreetingScreenshotTest {

    @get:Rule val composeTestRule = createComposeRule()

    @Test
    fun noteCard_screenshot() {
        val sample = NoteEntity(
            id = 1,
            title = "Ahmed – Galala Marble Prices",
            body = "بكرة لازم أكلم أحمد بتاع الرخام بخصوص أسعار الجلالة لمشروع New Cairo",
            sourceType = NoteSourceType.VOICE.name,
            createdAt = System.currentTimeMillis() - 3600_000L,
            durationMs = 45000L,
            isPinned = true,
            titleWasAutoGenerated = true
        )

        composeTestRule.setContent {
            MyApplicationTheme {
                NoteCard(
                    note = sample,
                    onClick = {},
                    onTogglePin = {}
                )
            }
        }

        composeTestRule.onRoot().captureRoboImage(filePath = "src/test/screenshots/note_card.png")
    }
}
